In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [19]:
df = pd.read_csv("C:/Users/admin/OneDrive/maytinh/Downloads/New folder/META_stock_data.csv")

In [20]:
# # Chuyển đổi cột 'Date' sang định dạng datetime và sắp xếp theo ngày
# df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')
# df = df.sort_values(by='Date').reset_index(drop=True)

In [21]:
data = df['Close']

In [22]:
# Bước 2: Chuẩn bị dữ liệu
def prepare_data(data, n_days):
    X, y = [], []
    for i in range(len(data) - n_days):
        X.append(data[i:i+n_days])
        y.append(data[i+n_days])
    return np.array(X), np.array(y)

n_days = 21
X, y = prepare_data(data.values, n_days)
X

array([[  48.17399979,   48.93799973,   48.62599945, ...,   59.93600082,
          65.62599945,   65.54199982],
       [  48.93799973,   48.62599945,   46.60599899, ...,   65.62599945,
          65.54199982,   63.24399948],
       [  48.62599945,   46.60599899,   46.2859993 , ...,   65.54199982,
          63.24399948,   63.0019989 ],
       ...,
       [ 858.9699707 ,  838.29998779,  795.34997559, ..., 1145.44995117,
        1091.26000977, 1045.76000977],
       [ 838.29998779,  795.34997559,  766.36999512, ..., 1091.26000977,
        1045.76000977, 1057.26000977],
       [ 795.34997559,  766.36999512,  801.89001465, ..., 1045.76000977,
        1057.26000977, 1025.48999023]])

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)


LinearRegression()

In [24]:
y_pred = model.predict(X_test)
model.coef_

array([ 0.03769934,  0.00384245, -0.07511277,  0.05682786,  0.01879876,
       -0.0587103 ,  0.07143143, -0.04073535, -0.0898251 ,  0.19722907,
       -0.06315562, -0.05259291,  0.05796449, -0.14216898,  0.0978181 ,
       -0.07024463,  0.01369176,  0.02602106,  0.03575858, -0.01217194,
        0.98677201])

In [25]:
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error,r2_score

mse = mean_squared_error(y_test, y_pred,squared=False)
mape = mean_absolute_percentage_error(y_test, y_pred)
r2 = r2_score(y_test,y_pred)
print('rmse:',mse)
print('mape',mape)
print('r_2',r2)

rmse: 23.110182208734315
mape 0.034918961203826614
r_2 0.99457385766584


In [26]:
# Dự đoán giá cổ phiếu cho ngày tiếp theo
next_day_prediction = model.predict([data.values[-n_days:]])
next_day_prediction

array([962.37245271])

In [27]:
from sklearn.linear_model import Ridge

# Mô hình Ridge Regression
ridge_model = Ridge(alpha=0.1)
ridge_model.fit(X_train, y_train)


Ridge(alpha=0.1)

In [28]:
y_pred_ri = ridge_model.predict(X_test)

In [29]:
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error

mse2 = mean_squared_error(y_test, y_pred_ri,squared=False)
mape2 = mean_absolute_percentage_error(y_test, y_pred_ri)
r_2rr = r2_score(y_test,y_pred_ri)
print('rmse:',mse2)
print('mape',mape2)
print('r_2',r_2rr)

rmse: 23.11018245421601
mape 0.03491896148699856
r_2 0.9945738575505645
